# Site settings
title:       Software Crafters Manila
email:       ''
description: ''
baseurl:     ''
url:         'https://softwarecraftersmanila.github.io/'
github:      'https://github.com/softwarecraftersmanila'
facebook:    'https://www.facebook.com/groups/softwarecraftersmanila'

markdown:  kramdown
permalink: pretty
paginate:  60

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext